### ISSUE TITLE
Update shiftcrypto/bitbox-wallet-app:22 docker image to bump golangci-lint

### ISSUE THREAD

**Issue by baizon** [BitBoxSwiss/bitbox-wallet-app#2755]
Hi, 
I solved all the golangci-lint issues (https://github.com/baizon/bitbox-wallet-app/pull/1) within your project, also updated the `.golangci.yml` to match version `1.59.0`. Your `github-ci.sh` uses the `shiftcrypto/bitbox-wallet-app:22` image, which contains `golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z`. Could you please update golangci-lint within the image, so I can make a pull request. With the new version I would also add the `golangci-lint config verify` to check the `.golangci.yml` (see: https://github.com/baizon/bitbox-wallet-app/commit/ccf65a6b7567c1a4db1fd63efbb250e5bc28c445).
Thanks in advance.

**Comment by benma** [comment]
Thanks! I pushed a new image with tag number 23 (we don't edit existing images). Please use that one in scripts/github-ci.sh and in .github/workflows/ci.yml

**Comment by baizon** [comment]
Thank You, worked perfectly. PR for that: https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2758
