### ISSUE TITLE
[Feature Request] Allow Mobile App to display account values while BitBox is not connected

### ISSUE THREAD

**Issue by kayserlein** [BitBoxSwiss/bitbox-wallet-app#2909]
It would be great if we could see the values in our wallet via the mobile app (Android in my case) without having to have the BitBox connected. 

Of course, for security reasons, it would be better to still have Sending/Receiving and other functionalities like Buying Crypto locked behind having the wallet connected but the mere display of owned coins and their value in Fiat would hopefully not pose a security issue as it would basically just be reading out data that is on the blockchain (similar to the Linux app)? 

If there is concern about users automaticaly enabling this for some security reasons, it could be mandatory to tick a list of individual checkboxes first, like when setting up the Backup SD card.

Thank you in advance for considering this.

**Comment by thisconnect** [comment]
@kayserlein you can enable "remember wallet" under settings > manage accounts, see also:

https://bitbox.swiss/blog/bitbox-12-2023-sustli-update/#remember-wallet

**Comment by kayserlein** [comment]
Apologies, I completely overlooked this. Thank you 🙏
