### ISSUE TITLE
Static IV in key generation

### ISSUE THREAD

**Issue by jafalter** [BitBoxSwiss/bitbox-wallet-app#2929]
I wanted to examine how keys are generated when creating a new wallet. I found the `/create/wallet` call which ultimately calls the `seed` function in the `device.go` file, which calls the `stretchKey` function below (whereas the backupPassword is passed as key parameter) to generate a key using the [pbkdf2](https://pkg.go.dev/golang.org/x/crypto/pbkdf2) package.
It seems that a static string "Digitial Bitbox" is passed to pbkdf2 as initialization vector which is insecure.

```go
func stretchKey(key string) string {
	const (
		iterations = 20480
		keylen     = 64
	)
	first := hex.EncodeToString(pbkdf2.Key(
		[]byte(key),
		[]byte("Digital Bitbox"),
		iterations,
		keylen,
		sha512.New))
	second := hex.EncodeToString(pbkdf2.Key(
		[]byte(key),
		[]byte("Digital Bitbox"),
		iterations,
		keylen,
		sha512.New))
	if first != second {
		panic("memory error")
	}
	return first
}
```
From https://pkg.go.dev/golang.org/x/crypto/pbkdf2: `Remember to get a good random salt. At least 8 bytes is recommended by the RFC.`

**Comment by benma** [comment]
Thanks for opening an issue.

This code relates to the BitBox01, which is not officially supported or maintained anymore for a very long time already.

See https://support.bitbox.swiss/bitbox01-end-of-salelife-faqs

If you are still using a BitBox01, I encourage you to switch to BitBox02.

If you are already a BitBox02 user and want to learn more about how the wallet is created there, please let me know.
