### ISSUE TITLE
Date text overlap in tx history

### ISSUE THREAD

**Issue by dzdidi** [BitBoxSwiss/bitbox-wallet-app#2975]
Platform: Google Pixel 5.
App version: 4.43.0
Issue:
> When date is `DD/MM/YYYY` (two digit day and two digit month) text gets overlap (see attachment) 
![Untitled](https://github.com/user-attachments/assets/a4244775-b49a-49b3-84c8-12edfd362707)

**Comment by thisconnect** [comment]
thanks for reporting, this will be fixed in the next release, see also https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2936
